// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8YPE__aE0Tsl3_MU0jHpTatAXMHKDCUI',
    appId: '1:798195357734:web:f9e364bd4ce17b489e2ee7',
    messagingSenderId: '798195357734',
    projectId: 'imagebook-b13cd',
    authDomain: 'imagebook-b13cd.firebaseapp.com',
    storageBucket: 'imagebook-b13cd.firebasestorage.app',
    measurementId: 'G-3S67D8SMHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR5B3IUnXZu6u0lZdQdHZCGEf_QDPIhIw',
    appId: '1:798195357734:android:919bc9cbf78c8f819e2ee7',
    messagingSenderId: '798195357734',
    projectId: 'imagebook-b13cd',
    storageBucket: 'imagebook-b13cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnEaJvuxnFKDtIqkcpE99dQ9kbs9gdB8g',
    appId: '1:798195357734:ios:3fe998a74814a7869e2ee7',
    messagingSenderId: '798195357734',
    projectId: 'imagebook-b13cd',
    storageBucket: 'imagebook-b13cd.firebasestorage.app',
    iosBundleId: 'com.example.imagebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnEaJvuxnFKDtIqkcpE99dQ9kbs9gdB8g',
    appId: '1:798195357734:ios:3fe998a74814a7869e2ee7',
    messagingSenderId: '798195357734',
    projectId: 'imagebook-b13cd',
    storageBucket: 'imagebook-b13cd.firebasestorage.app',
    iosBundleId: 'com.example.imagebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8YPE__aE0Tsl3_MU0jHpTatAXMHKDCUI',
    appId: '1:798195357734:web:3fed892b01e1c2ac9e2ee7',
    messagingSenderId: '798195357734',
    projectId: 'imagebook-b13cd',
    authDomain: 'imagebook-b13cd.firebaseapp.com',
    storageBucket: 'imagebook-b13cd.firebasestorage.app',
    measurementId: 'G-LMC6YYE3RS',
  );
}
